name: Memory Hole
#description: 
#meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            http://alzabo.io
author:         Ryan Cunningham
